name: Ping Server

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: |
          curl -s https://pharmapoly-server.onrender.com/keep-alive > /dev/null
